config/routes.rb
Project1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',   via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/projects', to: 'static_pages#projects', via: 'get'
  root 'static_pages#home'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
	validates :title, presence: true, length: { maximum: 140 }
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    					uniqueness: { case_sensitive: false }
    validates :password, length: { minimum: 6 }
    has_secure_password

    def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.digest(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

    def feed
      Post.where("user_id = ?", id)
    end

  	private

    	def create_remember_token
      		self.remember_token = User.digest(User.new_remember_token)
    	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user, only: [:create, :destroy]
	before_action :correct_user,   only: :destroy

	def index
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created!"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_url
	end

	private

		def post_params
			params.require(:post).permit(:title, :content)
		end

		def correct_user
			@post = current_user.posts.find_by(id: params[:id])
			redirect_to root_url if @post.nil?
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
    	user = User.find_by(email: params[:session][:email].downcase)
    	if user && user.authenticate(params[:session][:password])
    		sign_in user
    		redirect_back_or user
    	else
      		flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      		render 'new'
    	end
  	end

	def destroy 
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def projects
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user,   only: [:index, :edit, :update, :destroy]
	before_action :correct_user,	 only: [:edit, :update]
	before_action :admin_user,		 only: :destroy

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page])
	end

	def new 
		@user = User.new
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated!"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash.now[:success] = "Welcome!"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted."
		redirect_to users_url
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password,
										:password_confirmation)
		end

		#Before filters

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    	user.update_attribute(:remember_token, User.digest(remember_token))
    	self.current_user = user
  	end

  	def signed_in?
  		!current_user.nil?
  	end

  	def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	remember_token = User.digest(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

    def current_user?(user)
      user == current_user
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in" 
      end
    end

  	def sign_out
    	current_user.update_attribute(:remember_token,
        	                          User.digest(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
	  end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def store_location
      session[:return_to] = request.url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
	<nav>
    <ul class="nav">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
      <div class="container">
          <nav>
            <ul class="nav">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Contact",    contact_path %></li>
              <li><%= link_to "About", about_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path %></li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
            </ul>
          </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pacholewicz.com - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="main container">
  		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/_post.html.erb
<li>
  <span class="title"><%= post.title %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user?(post.user) %>
  	<% link_to "delete", post, method: :delete,
  								data: { confirm: "You sure?" },
  								title: post.title %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error">
	<div class="error">
		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
	<% object.errors.full_messages.each do |msg| %>
		<li> * <%= msg %> </li>
	<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="posts">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="title"><%= feed_item.title %></span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.title %>
  <% end %>
</li>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
	<%render 'shared/error_messages', object: f.object %>
	<div class="">
		<%= f.text_area :title, placeholder: "Title" %>
		<%= f.text_area :content, placeholder: "Compose new post" %>
	</div>
	<%= f.submit "Post", class: "" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if signed_in? %>
  <div class="">
    <aside class="">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/post_form' %>
      </section>
    </aside>
    <div class="">
      <h3>Post feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>


    <%= link_to "Sign up now!", signup_path,
                                class: "" %>
  </div>
<% end %>

app/views/static_pages/projects.html.erb
<h1>Projects</h1>

app/views/users/_user.html.erb
<li>
<%= link_to user.name, user %>
<% if current_user.admin? && !current_user?(user) %>
 | <%= link_to "delete", user, method: :delete, 
 						data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1> Update your profile</h1>

<div class="">
	<div class="">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "" %>

		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1> All users </h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h2>Sign up</h2>

<div class="">
  <div class="">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h2><%= @user.name %></h2>

<div class="">
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>